
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.jboss.as.quickstarts.ws_security.wsclient;

import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-02-29T14:34:30.541-05:00
 * Generated source version: 2.4.6
 * 
 */


/*@javax.jws.WebService(
                      serviceName = "SecuredService",
                      portName = "SecuredServicePort",
                      targetNamespace = "http://jboss.org/as/quickstarts/wssecurity",
                      //wsdlLocation = "http://localhost:8080/ws-security/SecuredService?wsdl",
                      endpointInterface = "org.jboss.as.quickstarts.ws_security.wsclient.SecuredService")
@HandlerChain(file="/jaxws-chain-handler-config.xml")*/                      
public class SecuredServiceImpl implements SecuredService {

    private static final Logger LOG = Logger.getLogger(SecuredServiceImpl.class.getName());

    public java.lang.String callSecuredWSMethod() { 
        LOG.info("Executing operation callSecuredWSMethod");
        try {
            java.lang.String _return = "_return-772260185";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
