
package org.jboss.as.quickstarts.ws_security.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-02-29T14:34:30.493-05:00
 * Generated source version: 2.4.6
 * 
 */
public final class SecuredService_SecuredServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://jboss.org/as/quickstarts/wssecurity", "SecuredService");

    private SecuredService_SecuredServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SecuredService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SecuredService_Service ss = new SecuredService_Service(wsdlURL, SERVICE_NAME);
        SecuredService port = ss.getSecuredServicePort();  
        
        {
        System.out.println("Invoking callSecuredWSMethod...");
        java.lang.String _callSecuredWSMethod__return = port.callSecuredWSMethod();
        System.out.println("callSecuredWSMethod.result=" + _callSecuredWSMethod__return);


        }

        System.exit(0);
    }

}
