package org.jboss.as.quickstarts.ws_security.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-02-29T14:34:30.554-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://jboss.org/as/quickstarts/wssecurity", name = "SecuredService")
@XmlSeeAlso({ObjectFactory.class})
public interface SecuredService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "callSecuredWSMethod", targetNamespace = "http://jboss.org/as/quickstarts/wssecurity", className = "org.jboss.as.quickstarts.ws_security.wsclient.CallSecuredWSMethod")
    @WebMethod
    @ResponseWrapper(localName = "callSecuredWSMethodResponse", targetNamespace = "http://jboss.org/as/quickstarts/wssecurity", className = "org.jboss.as.quickstarts.ws_security.wsclient.CallSecuredWSMethodResponse")
    public java.lang.String callSecuredWSMethod();
}
